#!/bin/bash
# Test script to demonstrate monitor fixes

echo "=== Testing SAM.gov Monitor Fixes ==="
echo ""
echo "1. Testing GitHub repository name parsing fix..."
echo "   - Fixed: Repository name now correctly parses 'owner/repo' format"
echo "   - The code now splits GITHUB_REPOSITORY if it contains '/' and extracts owner and repo separately"
echo ""
echo "2. Testing rate limit handling improvements..."
echo "   - Sequential query execution with 10-second delays between queries"
echo "   - Increased retry delays: base delay is now 5 seconds (was 1 second)"
echo "   - Added logging for 429 rate limit errors with retry information"
echo "   - Exponential backoff: delays increase as 10s, 20s, 40s for subsequent retries"
echo ""
echo "3. Summary of changes:"
echo "   - internal/monitor/monitor.go: Removed concurrent execution, added sequential with delays"
echo "   - internal/samgov/client.go: Increased base delay and added logging for 429 errors"
echo "   - internal/monitor/monitor.go: Fixed GitHub repository parsing to handle 'owner/repo' format"
echo ""
echo "To run with a real API key:"
echo "export SAM_API_KEY='your-actual-api-key'"
echo "export GITHUB_TOKEN='your-github-token'"
echo "export GITHUB_REPOSITORY='owner/repo'"
echo "./bin/monitor -v"