queries:
  - name: "Defense & Security AI Systems"
    enabled: true
    parameters:
      ptype: ["o", "k", "p", "r", "s"]
      title: "artificial intelligence"
    notification:
      priority: high
      recipients: ["danieltuckerrust@gmail.com"]
      channels: ["email", "github"]
    advanced:
      include: ["edge AI", "edge computing", "adaptive AI", "autonomous AI", "self-learning", "neuromorphic", "brain-inspired", "collaborative AI", "distributed AI", "AI platform", "AI framework", "AI deployment", "threat detection", "anomaly detection", "pattern recognition", "real-time AI", "on-device AI", "AI inference", "embedded AI", "defense AI", "military AI", "border security", "surveillance AI", "counter-UAS", "counter-drone", "AI drone", "autonomous drone", "computer vision", "object detection", "video analytics", "AI camera", "smart sensor", "sensor fusion", "multi-modal AI", "AI tower", "perimeter security", "maritime AI", "AI box", "edge device"]
      exclude: ["medical", "patient", "health", "hospital", "clinical", "diagnosis", "treatment", "therapy", "pharmaceutical", "drug", "FDA", "healthcare", "biomedical", "education", "teaching", "curriculum", "student", "school", "university", "academic", "research only", "study only", "theoretical", "simulation only"]
      maxDaysOld: 90