queries:
  - name: "Artificial Intelligence"
    enabled: true
    parameters:
      ptype: ["s", "p", "o"]
      title: "artificial intelligence AI"
    notification:
      priority: high
      recipients: ["danieltuckerrust@gmail.com"]
      channels: ["email", "github"]
    advanced:
      include: ["AI", "machine learning", "neural network", "deep learning"]
      maxDaysOld: 60