queries:
  - name: "Artificial Intelligence"
    enabled: true
    parameters:
      ptype: ["o"]
      title: "artificial intelligence"
    notification:
      priority: high
      recipients: ["danieltuckerrust@gmail.com"]
      channels: ["email", "github"]
    advanced:
      include: ["AI", "machine learning", "neural network", "deep learning", "computer vision", "sensor fusion", "edge computing", "autonomous systems", "object detection", "threat detection"]
      maxDaysOld: 90