queries:
  - name: "Defense & Security AI Systems"
    enabled: true
    parameters:
      ptype: ["o", "k", "p", "r"]
      title: "system"
    notification:
      priority: high
      recipients: ["danieltuckerrust@gmail.com"]
      channels: ["email", "github"]
    advanced:
      include: ["artificial intelligence", "machine learning", "autonomous system", "intrusion detection system", "video surveillance system", "maritime surveillance", "cybersecurity", "cyber security", "threat detection", "surveillance camera", "drone detection", "border security", "computer vision", "deep learning", "neural network", "video analytics", "AI system", "ML platform", "intelligent surveillance", "smart sensor", "biometric", "facial recognition", "object detection", "perimeter security", "situational awareness", "wide-area surveillance", "terrain awareness", "anomaly detection", "pattern recognition", "automated detection", "wrong way detection", "counter-UAS", "counter-drone"]
      exclude: ["medical", "patient", "health", "hospital", "chlorine", "water quality", "environmental monitoring", "HVAC", "heating", "cooling", "fire suppression", "kitchen", "maintenance only", "repair only"]
      maxDaysOld: 90