queries:
  # Single focused search: Artificial Intelligence
  - name: "Artificial Intelligence Opportunities"
    enabled: true
    parameters:
      ptype: ["o", "k", "p", "r", "s"]
      title: "artificial intelligence"
    notification:
      priority: high
      recipients: ["danieltuckerrust@gmail.com"]
      channels: ["email", "github"]
    advanced:
      # Minimal exclusions only - cast a wide net
      exclude: ["medical", "healthcare", "education", "academic"]