queries:
  - name: "Defense & Security AI Systems"
    enabled: true
    parameters:
      ptype: ["o", "k", "p", "r"]
      title: "surveillance"
    notification:
      priority: high
      recipients: ["danieltuckerrust@gmail.com"]
      channels: ["email", "github"]
    advanced:
      include: ["AI", "artificial intelligence", "detection", "monitoring", "autonomous", "sensor", "camera", "tower", "drone", "border security", "threat detection"]
      maxDaysOld: 90